# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_geovallecvc.ui'
#
# Created: Fri Mar 28 17:01:41 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_geovallecvc(object):
    def setupUi(self, geovallecvc):
        geovallecvc.setObjectName(_fromUtf8("geovallecvc"))
        geovallecvc.resize(536, 401)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geovallecvc/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        geovallecvc.setWindowIcon(icon)
        self.buttonBox = QtGui.QDialogButtonBox(geovallecvc)
        self.buttonBox.setGeometry(QtCore.QRect(190, 370, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.toolBox = QtGui.QToolBox(geovallecvc)
        self.toolBox.setGeometry(QtCore.QRect(10, 10, 521, 361))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 521, 226))
        self.page.setObjectName(_fromUtf8("page"))
        self.label = QtGui.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(30, 40, 51, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.cp_e = QtGui.QLineEdit(self.page)
        self.cp_e.setGeometry(QtCore.QRect(100, 40, 151, 31))
        self.cp_e.setObjectName(_fromUtf8("cp_e"))
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.cp_n = QtGui.QLineEdit(self.page)
        self.cp_n.setGeometry(QtCore.QRect(100, 80, 151, 31))
        self.cp_n.setObjectName(_fromUtf8("cp_n"))
        self.cp_calcular = QtGui.QPushButton(self.page)
        self.cp_calcular.setGeometry(QtCore.QRect(290, 50, 181, 31))
        self.cp_calcular.setDefault(False)
        self.cp_calcular.setFlat(False)
        self.cp_calcular.setObjectName(_fromUtf8("cp_calcular"))
        self.cp_r = QtGui.QLineEdit(self.page)
        self.cp_r.setGeometry(QtCore.QRect(150, 140, 151, 31))
        self.cp_r.setObjectName(_fromUtf8("cp_r"))
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(130, 10, 111, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_15 = QtGui.QLabel(self.page)
        self.label_15.setGeometry(QtCore.QRect(30, 150, 131, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_19 = QtGui.QLabel(self.page)
        self.label_19.setGeometry(QtCore.QRect(330, 140, 171, 61))
        self.label_19.setText(_fromUtf8(""))
        self.label_19.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geovallecvc/logo_g.png")))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.pushButton = QtGui.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(260, 90, 20, 20))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 521, 226))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.ca_e = QtGui.QLineEdit(self.page_4)
        self.ca_e.setGeometry(QtCore.QRect(90, 40, 151, 31))
        self.ca_e.setObjectName(_fromUtf8("ca_e"))
        self.label_12 = QtGui.QLabel(self.page_4)
        self.label_12.setGeometry(QtCore.QRect(20, 80, 46, 13))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.ca_n = QtGui.QLineEdit(self.page_4)
        self.ca_n.setGeometry(QtCore.QRect(90, 80, 151, 31))
        self.ca_n.setObjectName(_fromUtf8("ca_n"))
        self.label_13 = QtGui.QLabel(self.page_4)
        self.label_13.setGeometry(QtCore.QRect(120, 10, 111, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.ca_calcular = QtGui.QPushButton(self.page_4)
        self.ca_calcular.setGeometry(QtCore.QRect(280, 50, 181, 31))
        self.ca_calcular.setDefault(False)
        self.ca_calcular.setFlat(False)
        self.ca_calcular.setObjectName(_fromUtf8("ca_calcular"))
        self.label_14 = QtGui.QLabel(self.page_4)
        self.label_14.setGeometry(QtCore.QRect(20, 40, 51, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.ca_r = QtGui.QLineEdit(self.page_4)
        self.ca_r.setGeometry(QtCore.QRect(150, 140, 151, 31))
        self.ca_r.setObjectName(_fromUtf8("ca_r"))
        self.label_16 = QtGui.QLabel(self.page_4)
        self.label_16.setGeometry(QtCore.QRect(20, 150, 131, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_20 = QtGui.QLabel(self.page_4)
        self.label_20.setGeometry(QtCore.QRect(330, 140, 171, 61))
        self.label_20.setText(_fromUtf8(""))
        self.label_20.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geovallecvc/logo_g.png")))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.pushButton_2 = QtGui.QPushButton(self.page_4)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 90, 20, 20))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 521, 226))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.cgms_lon_g = QtGui.QLineEdit(self.page_3)
        self.cgms_lon_g.setGeometry(QtCore.QRect(100, 50, 41, 31))
        self.cgms_lon_g.setObjectName(_fromUtf8("cgms_lon_g"))
        self.label_4 = QtGui.QLabel(self.page_3)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 51, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.cgms_lat_g = QtGui.QLineEdit(self.page_3)
        self.cgms_lat_g.setGeometry(QtCore.QRect(100, 90, 41, 31))
        self.cgms_lat_g.setObjectName(_fromUtf8("cgms_lat_g"))
        self.label_5 = QtGui.QLabel(self.page_3)
        self.label_5.setGeometry(QtCore.QRect(90, 10, 61, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.cgms_calcular = QtGui.QPushButton(self.page_3)
        self.cgms_calcular.setGeometry(QtCore.QRect(280, 60, 181, 31))
        self.cgms_calcular.setObjectName(_fromUtf8("cgms_calcular"))
        self.label_6 = QtGui.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(20, 50, 71, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.cgms_r = QtGui.QLineEdit(self.page_3)
        self.cgms_r.setGeometry(QtCore.QRect(140, 150, 151, 31))
        self.cgms_r.setObjectName(_fromUtf8("cgms_r"))
        self.cgms_lat_m = QtGui.QLineEdit(self.page_3)
        self.cgms_lat_m.setGeometry(QtCore.QRect(150, 90, 41, 31))
        self.cgms_lat_m.setObjectName(_fromUtf8("cgms_lat_m"))
        self.cgms_lon_m = QtGui.QLineEdit(self.page_3)
        self.cgms_lon_m.setGeometry(QtCore.QRect(150, 50, 41, 31))
        self.cgms_lon_m.setObjectName(_fromUtf8("cgms_lon_m"))
        self.cgms_lat_s = QtGui.QLineEdit(self.page_3)
        self.cgms_lat_s.setGeometry(QtCore.QRect(200, 90, 71, 31))
        self.cgms_lat_s.setObjectName(_fromUtf8("cgms_lat_s"))
        self.cgms_lon_s = QtGui.QLineEdit(self.page_3)
        self.cgms_lon_s.setGeometry(QtCore.QRect(200, 50, 71, 31))
        self.cgms_lon_s.setObjectName(_fromUtf8("cgms_lon_s"))
        self.label_10 = QtGui.QLabel(self.page_3)
        self.label_10.setGeometry(QtCore.QRect(150, 10, 61, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.page_3)
        self.label_11.setGeometry(QtCore.QRect(210, 10, 71, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_17 = QtGui.QLabel(self.page_3)
        self.label_17.setGeometry(QtCore.QRect(20, 160, 131, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_21 = QtGui.QLabel(self.page_3)
        self.label_21.setGeometry(QtCore.QRect(320, 140, 171, 61))
        self.label_21.setText(_fromUtf8(""))
        self.label_21.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geovallecvc/logo_g.png")))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.pushButton_3 = QtGui.QPushButton(self.page_3)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 100, 20, 20))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 521, 226))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.cgd_w = QtGui.QLineEdit(self.page_2)
        self.cgd_w.setGeometry(QtCore.QRect(100, 50, 151, 31))
        self.cgd_w.setObjectName(_fromUtf8("cgd_w"))
        self.label_7 = QtGui.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(30, 90, 61, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.cgd_n = QtGui.QLineEdit(self.page_2)
        self.cgd_n.setGeometry(QtCore.QRect(100, 90, 151, 31))
        self.cgd_n.setObjectName(_fromUtf8("cgd_n"))
        self.label_8 = QtGui.QLabel(self.page_2)
        self.label_8.setGeometry(QtCore.QRect(90, 20, 201, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.cgd_calcular = QtGui.QPushButton(self.page_2)
        self.cgd_calcular.setGeometry(QtCore.QRect(290, 70, 181, 31))
        self.cgd_calcular.setObjectName(_fromUtf8("cgd_calcular"))
        self.label_9 = QtGui.QLabel(self.page_2)
        self.label_9.setGeometry(QtCore.QRect(30, 50, 71, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.cgd_r = QtGui.QLineEdit(self.page_2)
        self.cgd_r.setGeometry(QtCore.QRect(150, 150, 151, 31))
        self.cgd_r.setObjectName(_fromUtf8("cgd_r"))
        self.label_18 = QtGui.QLabel(self.page_2)
        self.label_18.setGeometry(QtCore.QRect(30, 160, 131, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_22 = QtGui.QLabel(self.page_2)
        self.label_22.setGeometry(QtCore.QRect(330, 130, 171, 61))
        self.label_22.setText(_fromUtf8(""))
        self.label_22.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/geovallecvc/logo_g.png")))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.pushButton_4 = QtGui.QPushButton(self.page_2)
        self.pushButton_4.setGeometry(QtCore.QRect(260, 100, 20, 20))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 521, 226))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.label_24 = QtGui.QLabel(self.page_5)
        self.label_24.setGeometry(QtCore.QRect(0, 0, 511, 221))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.toolBox.addItem(self.page_5, _fromUtf8(""))

        self.retranslateUi(geovallecvc)
        self.toolBox.setCurrentIndex(4)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), geovallecvc.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), geovallecvc.reject)
        QtCore.QObject.connect(self.cp_calcular, QtCore.SIGNAL(_fromUtf8("clicked()")), geovallecvc.cplanas_calculo)
        QtCore.QObject.connect(self.cgd_calcular, QtCore.SIGNAL(_fromUtf8("clicked()")), geovallecvc.cgeodeg_calculo)
        QtCore.QObject.connect(self.ca_calcular, QtCore.SIGNAL(_fromUtf8("clicked()")), geovallecvc.cplanasarena_calculo)
        QtCore.QObject.connect(self.cgms_calcular, QtCore.SIGNAL(_fromUtf8("clicked()")), geovallecvc.cgeogms_calculo)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), geovallecvc.limpiar1)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), geovallecvc.limpiar2)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), geovallecvc.limpiar3)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), geovallecvc.limpiar4)
        QtCore.QMetaObject.connectSlotsByName(geovallecvc)

    def retranslateUi(self, geovallecvc):
        geovallecvc.setWindowTitle(_translate("geovallecvc", "Calculo ondulación Geoidal - Modelo (GEOVALLE 1.0 )", None))
        self.label.setText(_translate("geovallecvc", "Este (m):", None))
        self.cp_e.setText(_translate("geovallecvc", "1086592.71953", None))
        self.label_2.setText(_translate("geovallecvc", "Norte(m):", None))
        self.cp_n.setText(_translate("geovallecvc", "863582.836345", None))
        self.cp_calcular.setText(_translate("geovallecvc", "Calcular Ondulación Geoidal", None))
        self.label_3.setText(_translate("geovallecvc", "Coordenadas planas", None))
        self.label_15.setText(_translate("geovallecvc", "Ondulación geoidal (m):", None))
        self.pushButton.setText(_translate("geovallecvc", "*", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("geovallecvc", "Coordenadas planas (MAGNA-OESTE) - EPSG:3115", None))
        self.ca_e.setText(_translate("geovallecvc", "1086598.80202", None))
        self.label_12.setText(_translate("geovallecvc", "Norte(m):", None))
        self.ca_n.setText(_translate("geovallecvc", "863572.223333", None))
        self.label_13.setText(_translate("geovallecvc", "Coordenadas planas", None))
        self.ca_calcular.setText(_translate("geovallecvc", "Calcular Ondulación Geoidal", None))
        self.label_14.setText(_translate("geovallecvc", "Este(m):", None))
        self.label_16.setText(_translate("geovallecvc", "Ondulación geoidal (m):", None))
        self.pushButton_2.setText(_translate("geovallecvc", "*", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("geovallecvc", "Coordenadas planas (Bogota-OESTE \"ARENA\") - EPSG:21896", None))
        self.cgms_lon_g.setText(_translate("geovallecvc", "76", None))
        self.label_4.setText(_translate("geovallecvc", "Latitud(N):", None))
        self.cgms_lat_g.setText(_translate("geovallecvc", "3", None))
        self.label_5.setText(_translate("geovallecvc", "Grados (°)", None))
        self.cgms_calcular.setText(_translate("geovallecvc", "Calcular Ondulación Geoidal", None))
        self.label_6.setText(_translate("geovallecvc", "Longitud(W) :", None))
        self.cgms_lat_m.setText(_translate("geovallecvc", "21", None))
        self.cgms_lon_m.setText(_translate("geovallecvc", "17", None))
        self.cgms_lat_s.setText(_translate("geovallecvc", "43.855", None))
        self.cgms_lon_s.setText(_translate("geovallecvc", "53.982", None))
        self.label_10.setText(_translate("geovallecvc", "Minutos (\')", None))
        self.label_11.setText(_translate("geovallecvc", "Segundos (\'\')", None))
        self.label_17.setText(_translate("geovallecvc", "Ondulación geoidal (m):", None))
        self.pushButton_3.setText(_translate("geovallecvc", "*", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("geovallecvc", "Coordenadas geográficas (DMS) - EPSG:4326", None))
        self.cgd_w.setText(_translate("geovallecvc", "-76.2983282901", None))
        self.label_7.setText(_translate("geovallecvc", "Latitud (N):", None))
        self.cgd_n.setText(_translate("geovallecvc", "3.36218183162", None))
        self.label_8.setText(_translate("geovallecvc", "Coordenadas geográficas (Decimales)", None))
        self.cgd_calcular.setText(_translate("geovallecvc", "Calcular Ondulación Geoidal", None))
        self.label_9.setText(_translate("geovallecvc", "Longitud (W):", None))
        self.label_18.setText(_translate("geovallecvc", "Ondulación geoidal (m):", None))
        self.pushButton_4.setText(_translate("geovallecvc", "*", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("geovallecvc", "Coordenadas geográficas (Decimales)  - EPSG:4326", None))
        self.label_24.setText(_translate("geovallecvc", "Este plugin para QGIS entrega la ondulación geoidal para puntos de entrada en diferentes sistemas\n"
"de referencia en  el Valle del Cauca, para su cálculo hace uso del Geoide local (GEOVALLE 1.0) (OpenSource) \n"
"desarrollado por la corporación autónoma regional (CVC), el plugin desarrollado en python cumple \n"
"netamente fines académicos. Si desean conocer más acerca del proyecto GEOVALLE 1.0 contactar \n"
"directamente con sus creadores en la siguiente pagina Web:  \n"
"\n"
"http://geocvce.cvc.gov.co/  o en http://www.cvc.gov.co\n"
"\n"
"\n"
"Autor:\n"
"Mail: fandresherrera@hotmail.com  \n"
"Web:  http://andresherreracali.blogspot.com\n"
"\n"
"Santiago de Cali – Colombia – 28/Marzo/2014\n"
" *El autor del plugin expresa que no tienen ningún tipo de vinculo con la entidad CVC.", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("geovallecvc", "Acerda de este plugin", None))

import resources_rc
